In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from ydata_profiling import ProfileReport
from tqdm import tqdm

In [3]:
df=pd.read_csv('data.csv',sep=';')
df.head(10)

Marital status  Application mode  Application order  Course  \
0               1                17                  5     171   
1               1                15                  1    9254   
2               1                 1                  5    9070   
3               1                17                  2    9773   
4               2                39                  1    8014   
5               2                39                  1    9991   
6               1                 1                  1    9500   
7               1                18                  4    9254   
8               1                 1                  3    9238   
9               1                 1                  1    9238   

   Daytime/evening attendance\t  Previous qualification  \
0                             1                       1   
1                             1                       1   
2                             1                       1   
3                             1                       1   
4                             0                       1   
5                             0                      19   
6                             1                       1   
7                             1                       1   
8                             1                       1   
9                             1                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           122.0            1                      19   
1                           160.0            1                       1   
2                           122.0            1                      37   
3                           122.0            1                      38   
4                           100.0            1                      37   
5                           133.1            1                      37   
6                           142.0            1                      19   
7                           119.0            1                      37   
8                           137.0           62                       1   
9                           138.0            1                       1   

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0   
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   
5                      37  ...                                    0   
6                      38  ...                                    0   
7                      37  ...                                    0   
8                       1  ...                                    0   
9                      19  ...                                    0   

   Curricular units 2nd sem (enrolled)  \
0                                    0   
1                                    6   
2                                    6   
3                                    6   
4                                    6   
5                                    5   
6                                    8   
7                                    5   
8                                    6   
9                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   
5                                      17   
6                                       8   
7                                       5   
8                                       7   
9                                      14   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grad

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marital status                                  4424 non-null   int64  
 1   Application mode                                4424 non-null   int64  
 2   Application order                               4424 non-null   int64  
 3   Course                                          4424 non-null   int64  
 4   Daytime/evening attendance	                     4424 non-null   int64  
 5   Previous qualification                          4424 non-null   int64  
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64  
 8   Mother's qualification                          4424 non-null   int64  
 9   Father's qualification                   

In [5]:
df.describe()

Marital status  Application mode  Application order       Course  \
count     4424.000000       4424.000000        4424.000000  4424.000000   
mean         1.178571         18.669078           1.727848  8856.642631   
std          0.605747         17.484682           1.313793  2063.566416   
min          1.000000          1.000000           0.000000    33.000000   
25%          1.000000          1.000000           1.000000  9085.000000   
50%          1.000000         17.000000           1.000000  9238.000000   
75%          1.000000         39.000000           2.000000  9556.000000   
max          6.000000         57.000000           9.000000  9991.000000   

       Daytime/evening attendance\t  Previous qualification  \
count                   4424.000000             4424.000000   
mean                       0.890823                4.577758   
std                        0.311897               10.216592   
min                        0.000000                1.000000   
25%                        1.000000                1.000000   
50%                        1.000000                1.000000   
75%                        1.000000                1.000000   
max                        1.000000               43.000000   

       Previous qualification (grade)  Nacionality  Mother's qualification  \
count                     4424.000000  4424.000000             4424.000000   
mean                       132.613314     1.873192               19.561935   
std                         13.188332     6.914514               15.603186   
min                         95.000000     1.000000                1.000000   
25%                        125.000000     1.000000                2.000000   
50%                        133.100000     1.000000               19.000000   
75%                        140.000000     1.000000               37.000000   
max                        190.000000   109.000000               44.000000   

       Father's qualification  ...  \
count             4424.000000  ...   
mean                22.275316  ...   
std                 15.343108  ...   
min                  1.000000  ...   
25%                  3.000000  ...   
50%                 19.000000  ...   
75%                 37.000000  ...   
max                 44.000000  ...   

       Curricular units 1st sem (without evaluations)  \
count                                     4424.000000   
mean                                         0.137658   
std                                          0.690880   
min                                          0.000000   
25%                                          0.000000   
50%                                          0.000000   
75%                                          0.000000   
max                                         12.000000   

       Curricular units 2nd sem (credited)  \
count                          4424.000000   
mean                              0.541817   
std                               1.918546   
min                               0.000000   
25%                               0.000000   
50%                               0.000000   
75%                               0.000000   
max                              19.000000   

       Curricular units 2nd sem (enrolled)  \
count                          4424.000000   
mean                              6.232143   
std                               2.195951   
min                               0.000000   
25%                               5.000000   
50%                               6.000000   
75%                               7.000000   
max                              23.000000   

       Curricular units 2nd sem (evaluations)  \
count                             4424.000000   
mean                                 8.063291   
std                                  3.947951   
min                                  0.000000   
25%                                  6.000000   
50%                                  8.000000   
75%                           

In [6]:
def EncodeTarget(Target):
    dict={
        'Enrolled' :0,
        'Dropout' :1,
        'Graduate':2
    }
    return dict[Target]
df['Target']=df['Target'].apply(EncodeTarget)

In [7]:
def nomalized_data(df,col_names) :
    nomalized_df=df.copy()
    for col in col_names:
        mean=nomalized_df[col].mean()
        std=nomalized_df[col].std()
        nomalized_df[col]=(nomalized_df[col]-mean)/std
    return nomalized_df

In [36]:
col_to_nomalize=['Previous qualification (grade)',
                 'Inflation rate',
                 'GDP',
                 'Unemployment rate',
                 'Course']
nomalized_df=nomalized_data(df,col_to_nomalize)

In [37]:
nomalized_df.head()

Marital status  Application mode  Application order    Course  \
0               1                17                  5 -4.209044   
1               1                15                  1  0.192559   
2               1                 1                  5  0.103393   
3               1                17                  2  0.444065   
4               2                39                  1 -0.408343   

   Daytime/evening attendance\t  Previous qualification  \
0                             1                       1   
1                             1                       1   
2                             1                       1   
3                             1                       1   
4                             0                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                       -0.804750            1                      19   
1                        2.076585            1                       1   
2                       -0.804750            1                      37   
3                       -0.804750            1                      38   
4                       -2.472892            1                      37   

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0   
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   

   Curricular units 2nd sem (enrolled)  \
0                                    0   
1                                    6   
2                                    6   
3                                    6   
4                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0          -0.287606   
1                                               0           0.876123   
2                                               0          -0.287606   
3                                               0          -0.813161   
4                                               0           0.876123   

   Inflation rate       GDP  Target  
0        0.124372  0.765674       1  
1       -1.105097  0.347160       2  
2        0.124372  0.765674       1  
3       -1.466705 -1.375356       2  
4       -1.105097  0.347160       2  

[5 rows x 37 columns]

In [38]:
X=nomalized_df.iloc[:,:-1]
y=nomalized_df.iloc[:,-1]

In [39]:
encode_y=np.zeros((y.shape[0],3))
for i in range(encode_y.shape[0]):
    encode_y[i,y[i]]=1

In [43]:
encode_y

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [41]:
class SoftmaxRegression():
    def __init__(self,epoch,lr):
        self.lr=lr
        self.epoch=epoch
        self.acc_array=[]
        self.losses=[]

    def softmax(self, z):
        return np.exp(z)/np.sum(np.exp(z),axis=0)
    
    def loss_function(self, y, y_pred):
        return -((y*np.log(y_pred+1e-6)).sum(axis=-1)).mean()
    
    def accuracy(self,y,y_pred):
        return (1-np.abs(y-y_pred)).mean()
    
    def fit(self, X, y):
        n=X.shape[0]
        d=X.shape[1]
        num_class=y.shape[-1]
        self.theta=np.zeros((d,num_class))
        with tqdm(range(self.epoch)) as pb :
            for i in pb:
                pb.set_description(f"epoch :{i+1}")
                y_pred=self.predict(X)
                gradient=(1/n*np.matmul(X.T,(y_pred-y)))
                self.theta=self.theta-self.lr*gradient

                #evaluating
                y_pred=self.predict(X)
                loss=self.loss_function(y,y_pred)
                acc=self.accuracy(y.argmax(axis=-1),y_pred.argmax(axis=-1))
                pb.set_postfix({
                    "loss":loss,
                    "accuracy": acc
                })
                self.losses.append(loss)
                self.acc_array.append(acc)

    def predict(self, X):
        z=np.matmul(X,self.theta)
        y_pred=self.softmax(z)
        return y_pred

In [42]:
model=SoftmaxRegression(500,0.5)
model.fit(X,encode_y)
y_pred=model.predict(X)

epoch :1:   0%|          | 0/500 [00:00<?, ?it/s]c:\Users\minhk\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py:393: RuntimeWarning: overflow encountered in exp
  result = func(self.values, **kwargs)
epoch :1:   0%|          | 0/500 [00:00<?, ?it/s]


ValueError: No axis named -1 for object type DataFrame

In [15]:
y_pred=model.predict(X)
for i, j in zip(encode_y,y_pred):
    print(i ,j)

[0. 1. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 1. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 1. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 1. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 1. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 1. 0.] [nan nan nan]
[1. 0. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[1. 0. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[1. 0. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[1. 0. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[1. 0. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[1. 0. 0.] [nan nan nan]
[1. 0. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[1. 0. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 1. 0.] [nan nan nan]
[0. 1. 0.] [nan nan nan]
[0. 1. 0.] [nan nan nan]
[0. 0. 1.] [nan nan nan]
[0. 1. 0.] [nan nan nan]


In [16]:
def softmax(z):
    return np.exp(z)/np.sum(np.exp(z),axis=0)

In [17]:
theta=np.zeros((36,3))
z=np.matmul(X,theta)
y_pred=softmax(z)

In [18]:
y_pred

array([[0.00022604, 0.00022604, 0.00022604],
       [0.00022604, 0.00022604, 0.00022604],
       [0.00022604, 0.00022604, 0.00022604],
       ...,
       [0.00022604, 0.00022604, 0.00022604],
       [0.00022604, 0.00022604, 0.00022604],
       [0.00022604, 0.00022604, 0.00022604]])

In [19]:
print((y_pred-encode_y))

[[ 2.26039783e-04 -9.99773960e-01  2.26039783e-04]
 [ 2.26039783e-04  2.26039783e-04 -9.99773960e-01]
 [ 2.26039783e-04 -9.99773960e-01  2.26039783e-04]
 ...
 [ 2.26039783e-04 -9.99773960e-01  2.26039783e-04]
 [ 2.26039783e-04  2.26039783e-04 -9.99773960e-01]
 [ 2.26039783e-04  2.26039783e-04 -9.99773960e-01]]


In [20]:
gradient=(1/4424*np.matmul(X.T,(y_pred-encode_y)))

In [21]:
gradient*0.5

array([[-1.03279999e-01, -2.02398444e-01, -2.83207666e-01],
       [-1.77467574e+00, -3.80620829e+00, -3.74732492e+00],
       [-1.45713399e-01, -2.55681753e-01, -4.61943055e-01],
       [-7.94866564e+02, -1.40516426e+03, -2.22528756e+03],
       [-8.11606213e-02, -1.37105468e-01, -2.26843261e-01],
       [-4.28958210e-01, -8.52443743e-01, -1.00592476e+00],
       [ 9.55923972e-03,  1.82570253e-02, -2.78162650e-02],
       [-1.86384133e-01, -3.14096610e-01, -4.35479974e-01],
       [-1.57916343e+00, -3.37606669e+00, -4.81910466e+00],
       [-1.87485586e+00, -3.64045261e+00, -5.61479709e+00],
       [-1.31973769e+00, -1.62342214e+00, -2.53357133e+00],
       [-1.29622148e+00, -1.62748278e+00, -2.58871696e+00],
       [-1.12508162e+01, -2.00546024e+01, -3.21405879e+01],
       [-4.88756360e-02, -7.55483304e-02, -1.49576359e-01],
       [-1.24191591e-03, -1.92003526e-03, -2.59815461e-03],
       [-1.01589401e-02, -3.52493560e-02, -1.14021589e-02],
       [-8.48914273e-02, -1.08851644e-01

In [22]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(multi_class='multinomial')


In [23]:
print(X.shape, y.shape)

(4424, 36) (4424,)


In [24]:
model.fit(X,y)

c:\Users\minhk\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\minhk\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [25]:
y_pred=model.predict(X)

In [26]:
for i,j in zip(y,y_pred):
    print(f"y : {i} \t y_pred:{j}")

y : 1 	 y_pred:1
y : 2 	 y_pred:2
y : 1 	 y_pred:1
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 2 	 y_pred:1
y : 2 	 y_pred:2
y : 1 	 y_pred:1
y : 2 	 y_pred:2
y : 1 	 y_pred:2
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 1 	 y_pred:1
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 1 	 y_pred:1
y : 0 	 y_pred:2
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 0 	 y_pred:2
y : 2 	 y_pred:1
y : 0 	 y_pred:2
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 0 	 y_pred:2
y : 2 	 y_pred:2
y : 0 	 y_pred:2
y : 2 	 y_pred:2
y : 0 	 y_pred:2
y : 0 	 y_pred:0
y : 2 	 y_pred:2
y : 0 	 y_pred:2
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 1 	 y_pred:2
y : 1 	 y_pred:1
y : 1 	 y_pred:1
y : 2 	 y_pred:1
y : 1 	 y_pred:0
y : 1 	 y_pred:1
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 1 	 y_pred:2
y : 1 	 y_pred:1
y : 0 	 y_pred:2
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 2 	 y_pred:2
y : 0 	 y_pred:2
y : 0 	 y_pred:2
y : 2 	 y_pred:2
y : 1 	 y_pred:1
y : 2 	 y_pred:2
y : 1 	 y_pred:1
y : 1 	 y_pred:2
y : 2 	 y_pred

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       0.51      0.06      0.11       794
           1       0.74      0.67      0.70      1421
           2       0.67      0.93      0.78      2209

    accuracy                           0.69      4424
   macro avg       0.64      0.55      0.53      4424
weighted avg       0.67      0.69      0.64      4424

